#Network Shape

hidden_layer_1: 256 #Number of neurons in the first hidden layer
hidden_layer_2: 64 #Number of neurons in the second hidden layer
device: "cuda" #Device to use for training, set to "cpu" or "cuda"

#Learning Hyperparameters
learning_rate: 0.0005
batch_size: 128
dropout_rate: 0.2

#Seed
seed: 42   

#Training
max_epochs: 10

#Logging
wandb_project: mnist_deep_learning
use_wandb: true
group_name: "latest" #group name for wandb runs, set to None to disable grouping

#Optuna
use_optuna: false
optuna_trials: 100



